; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.40629.0 

	TITLE	C:\Users\Admin\documents\visual studio 2013\Projects\Win32Project1\Win32Project1\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	___@@_PchSym_@00@UfhvihUzwnrmUwlxfnvmghUerhfzoLhgfwrlLCABDUkilqvxghUdrmDCkilqvxgBUdrmDCkilqvxgBUivovzhvUhgwzucOlyq@5C1895386BBF8989
;	COMDAT ___@@_PchSym_@00@UfhvihUzwnrmUwlxfnvmghUerhfzoLhgfwrlLCABDUkilqvxghUdrmDCkilqvxgBUdrmDCkilqvxgBUivovzhvUhgwzucOlyq@5C1895386BBF8989
_BSS	SEGMENT
___@@_PchSym_@00@UfhvihUzwnrmUwlxfnvmghUerhfzoLhgfwrlLCABDUkilqvxghUdrmDCkilqvxgBUdrmDCkilqvxgBUivovzhvUhgwzucOlyq@5C1895386BBF8989 DD 01H DUP (?)
_BSS	ENDS
END
